variables:
  DOCKER_REGISTRY: registry.git.chalmers.se
  DOCKER_IMAGE: "${DOCKER_REGISTRY}/courses/dit355/student-teams/dit356-2023-03/dentist-app"

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$DOCKER_REGISTRY"

build_image:
  stage: build
  script:
    - docker pull "$DOCKER_IMAGE" || true
    - docker build -t "$DOCKER_IMAGE" .
    - docker push "$DOCKER_IMAGE"
    
stages:
    - build
    - test

build:
    stage: build
    script:
        - echo "Building"
        - mkdir build
        - touch build/info.txt
    artifacts:
        paths:
            - build/

test:
    stage: test
    script:
        - echo "Testing"
        - test -f "build/info.txt"
